create extension if not exists "pgcrypto";

create type public.member_status as enum ('pending', 'approved', 'rejected');
create type public.member_role as enum ('admin', 'member');
create type public.game_source as enum ('rawg', 'steam', 'custom');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 2 and 24),
  avatar_url text,
  status public.member_status not null default 'pending',
  role public.member_role not null default 'member',
  xp integer not null default 0 check (xp >= 0),
  level integer not null default 1 check (level > 0),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.site_settings (id boolean primary key default true check (id), site_title text not null default 'Party Clear', site_description text not null default '우리 모임의 게임 플레이와 리뷰', logo_url text, updated_at timestamptz not null default now());
insert into public.site_settings (id) values (true);
create table public.games (id uuid primary key default gen_random_uuid(), name text not null, cover_url text, source public.game_source not null, external_id text, price_krw integer not null default 0 check (price_krw >= 0), created_at timestamptz not null default now(), unique (source, external_id));
create table public.play_sessions (id uuid primary key default gen_random_uuid(), game_id uuid not null references public.games(id), cover_url text, memo text, total_play_minutes integer not null default 0, starts_at timestamptz, ends_at timestamptz, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.session_play_blocks (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.play_sessions(id) on delete cascade, started_at timestamptz not null, ended_at timestamptz not null, sort_order integer not null default 0, check (ended_at > started_at));
create table public.session_participants (session_id uuid not null references public.play_sessions(id) on delete cascade, profile_id uuid not null references public.profiles(id) on delete cascade, review_status text not null default 'pending' check (review_status in ('pending','submitted')), primary key(session_id, profile_id));
create table public.reviews (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.play_sessions(id) on delete cascade, profile_id uuid not null references public.profiles(id) on delete cascade, rating integer not null check (rating between 1 and 5), content text not null check (char_length(content) between 1 and 4000), tags jsonb not null default '[]'::jsonb, image_urls jsonb not null default '[]'::jsonb check (jsonb_array_length(image_urls) <= 3), recommended boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(session_id, profile_id));
create table public.achievements (id text primary key, title text not null, description text not null, threshold integer not null, unlock_type text not null);
create table public.user_achievements (profile_id uuid not null references public.profiles(id) on delete cascade, achievement_id text not null references public.achievements(id), unlocked_at timestamptz not null default now(), primary key(profile_id, achievement_id));
create table public.review_reactions (review_id uuid not null references public.reviews(id) on delete cascade, profile_id uuid not null references public.profiles(id) on delete cascade, emoji text not null check (emoji in ('👍','😂','🔥')), created_at timestamptz not null default now(), primary key(review_id, profile_id, emoji));
insert into public.achievements (id,title,description,threshold,unlock_type) values ('first-review','첫 발자국','첫 리뷰를 남겼어요.',1,'review_count'),('reviewer-5','리뷰어','리뷰 5개를 달성했어요.',5,'review_count'),('trophy','트로피 헌터','리뷰 10개를 달성했어요.',10,'review_count'),('veteran','베테랑 리뷰어','리뷰 25개를 달성했어요.',25,'review_count'),('regular','단골','연속 3회 세션에 참여했어요.',3,'session_streak');

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) $$;
create or replace function public.is_approved() returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.profiles where id = auth.uid() and status = 'approved') $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, display_name, avatar_url) values (new.id, coalesce(left(new.raw_user_meta_data->>'full_name',24), left(new.email,24), '플레이어'), new.raw_user_meta_data->>'avatar_url'); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create trigger profiles_touch before update on public.profiles for each row execute procedure public.touch_updated_at(); create trigger sessions_touch before update on public.play_sessions for each row execute procedure public.touch_updated_at(); create trigger reviews_touch before update on public.reviews for each row execute procedure public.touch_updated_at();
create or replace function public.recalculate_session() returns trigger language plpgsql security definer set search_path = public as $$ declare sid uuid := coalesce(new.session_id, old.session_id); begin update public.play_sessions set starts_at = (select min(started_at) from public.session_play_blocks where session_id=sid), ends_at = (select max(ended_at) from public.session_play_blocks where session_id=sid), total_play_minutes = coalesce((select sum(extract(epoch from (ended_at-started_at))/60)::integer from public.session_play_blocks where session_id=sid),0) where id=sid; return coalesce(new,old); end; $$;
create trigger blocks_recalculate after insert or update or delete on public.session_play_blocks for each row execute procedure public.recalculate_session();
create or replace function public.reward_review() returns trigger language plpgsql security definer set search_path = public as $$ declare extra integer := case when jsonb_array_length(new.image_urls) > 0 then 20 else 0 end + case when jsonb_array_length(new.tags) >= 3 then 10 else 0 end; begin update public.session_participants set review_status='submitted' where session_id=new.session_id and profile_id=new.profile_id; update public.profiles set xp=xp+50+extra, level=greatest(1,(xp+50+extra)/100+1) where id=new.profile_id; insert into public.user_achievements(profile_id,achievement_id) select new.profile_id,a.id from public.achievements a where a.unlock_type='review_count' and (select count(*) from public.reviews where profile_id=new.profile_id) >= a.threshold on conflict do nothing; return new; end; $$;
create trigger reviews_reward after insert on public.reviews for each row execute procedure public.reward_review();

alter table public.profiles enable row level security; alter table public.site_settings enable row level security; alter table public.games enable row level security; alter table public.play_sessions enable row level security; alter table public.session_play_blocks enable row level security; alter table public.session_participants enable row level security; alter table public.reviews enable row level security; alter table public.achievements enable row level security; alter table public.user_achievements enable row level security; alter table public.review_reactions enable row level security;
create policy "approved read profiles" on public.profiles for select using (public.is_approved() or id=auth.uid()); create policy "self update profile" on public.profiles for update using (id=auth.uid() or public.is_admin()) with check (id=auth.uid() or public.is_admin());
create policy "approved settings read" on public.site_settings for select using (public.is_approved()); create policy "admin settings write" on public.site_settings for all using (public.is_admin()) with check (public.is_admin());
create policy "approved games read" on public.games for select using (public.is_approved()); create policy "approved game write" on public.games for insert with check (public.is_approved()); create policy "approved game update" on public.games for update using (public.is_approved()) with check (public.is_approved());
create policy "approved sessions read" on public.play_sessions for select using (public.is_approved()); create policy "approved sessions insert" on public.play_sessions for insert with check (public.is_approved() and created_by=auth.uid()); create policy "owner admin session update" on public.play_sessions for update using (created_by=auth.uid() or public.is_admin()); create policy "owner admin session delete" on public.play_sessions for delete using (created_by=auth.uid() or public.is_admin());
create policy "approved blocks read" on public.session_play_blocks for select using (public.is_approved()); create policy "owner blocks write" on public.session_play_blocks for all using (exists(select 1 from public.play_sessions s where s.id=session_id and (s.created_by=auth.uid() or public.is_admin()))) with check (exists(select 1 from public.play_sessions s where s.id=session_id and (s.created_by=auth.uid() or public.is_admin())));
create policy "approved participants read" on public.session_participants for select using (public.is_approved()); create policy "owner participants write" on public.session_participants for all using (exists(select 1 from public.play_sessions s where s.id=session_id and (s.created_by=auth.uid() or public.is_admin()))) with check (exists(select 1 from public.play_sessions s where s.id=session_id and (s.created_by=auth.uid() or public.is_admin())));
create policy "approved reviews read" on public.reviews for select using (public.is_approved()); create policy "participant review insert" on public.reviews for insert with check (profile_id=auth.uid() and exists(select 1 from public.session_participants p where p.session_id=reviews.session_id and p.profile_id=auth.uid())); create policy "own admin reviews edit" on public.reviews for update using (profile_id=auth.uid() or public.is_admin()); create policy "own admin reviews delete" on public.reviews for delete using (profile_id=auth.uid() or public.is_admin());
create policy "approved achievements read" on public.achievements for select using (public.is_approved()); create policy "approved user achievements read" on public.user_achievements for select using (public.is_approved()); create policy "approved reactions read" on public.review_reactions for select using (public.is_approved()); create policy "own reactions write" on public.review_reactions for insert with check (public.is_approved() and profile_id=auth.uid()); create policy "own reactions delete" on public.review_reactions for delete using (profile_id=auth.uid() or public.is_admin());

revoke update on public.profiles from authenticated;
grant update (display_name, avatar_url) on public.profiles to authenticated;

insert into storage.buckets (id,name,public) values ('session-covers','session-covers',false),('review-images','review-images',false),('avatars','avatars',false),('site-assets','site-assets',false) on conflict do nothing;
create policy "approved storage read" on storage.objects for select using (bucket_id in ('session-covers','review-images','avatars','site-assets') and public.is_approved()); create policy "approved cover upload" on storage.objects for insert with check (bucket_id='session-covers' and public.is_approved()); create policy "avatar owner write" on storage.objects for all using (bucket_id='avatars' and (owner_id=auth.uid()::text or public.is_admin())) with check (bucket_id='avatars' and (owner_id=auth.uid()::text or public.is_admin())); create policy "review image owner write" on storage.objects for all using (bucket_id='review-images' and (owner_id=auth.uid()::text or public.is_admin())) with check (bucket_id='review-images' and (owner_id=auth.uid()::text or public.is_admin())); create policy "admin site asset write" on storage.objects for all using (bucket_id='site-assets' and public.is_admin()) with check (bucket_id='site-assets' and public.is_admin());
